pf4: Use SVG spinner
cockpit-project/cockpit-ostree pull request #173
Opened 2021-03-23 13:02 UTC by garrett

Addresses https://github.com/cockpit-project/cockpit/issues/15573

2021-03-23 13:02 UTC, garrett commented
This doesn't seem to work, but it also doesn't seem to break things.

My guess is that the version of PatternFly we're using for cockpit-ostree is too old. Once that's upgraded, this PR should work.

2021-03-23 13:13 UTC, KKoukiou commented
@garrett this needs that you change the PF version in the package.json

2021-03-23 15:24 UTC, garrett commented
package.json uses the same version as Cockpit, however, the spinners are still going the wrong way and I can't find any additional use of a React `<Spinner>` in the code.

2021-03-23 16:56 UTC, KKoukiou commented
> package.json uses the same version as Cockpit, however, the spinners are still going the wrong way and I can't find any additional use of a React `<Spinner>` in the code.

We are interested in @patternfly/react-core and it's not the same version as in Cockpit. 
https://github.com/cockpit-project/cockpit-ostree/blob/master/package.json#L53

2021-03-23 17:06 UTC, KKoukiou commented
Oh I know, there was a breaking change release of course.

2021-03-23 17:45 UTC, martinpitt commented
> I am not sure why the npm-update script does not want to update patternfly here.

It only updates minor versions, not major ones.

2021-03-24 13:41 UTC, martinpitt commented
Unblocked, please rebase.

2021-03-24 13:43 UTC, KKoukiou commented
> Unblocked, please rebase.

It's actually fine, there are not conflicts here. I will just test rebase locally and test it.

2021-03-24 13:48 UTC, KKoukiou requested changes

2021-03-24 13:48 UTC, KKoukiou commented on src/app.jsx
> +                            {!(!!client.local_running || !!progressMsg) ? _("Check for Updates") : <Spinner isSVG size="sm" />}
This should be changed to use isLoading property.

2021-03-24 13:55 UTC, KKoukiou approved these changes

2021-03-24 14:13 UTC, merged