Use card for repository setting
cockpit-project/cockpit-ostree pull request #339
Opened 2023-02-28 14:23 UTC by marusak

Looks like this:
![Screenshot from 2023-02-28 14-04-09](https://user-images.githubusercontent.com/12330670/221881799-3c9a9832-8a7e-49a1-957c-7fe75d81e2b8.png)

Tests is broken and trying to understand why. Posting for now for design review

2023-02-28 14:51 UTC, marusak commented on cockpit-ostree.spec.in
> -%license LICENSE dist/ostree.js.LICENSE.txt.gz
oops :)

2023-03-01 13:25 UTC, garrett commented
What you've implemented is a very rough first pass I did a few years ago. Not the current design.

The current design supposed to be like this (from https://github.com/cockpit-project/cockpit-ostree/issues/176#issuecomment-1428184241):

![image](https://user-images.githubusercontent.com/10246/222127621-e773cc2a-4243-4751-8cea-9fa4c4c9dc46.png)

And editing it would open a modal.

I had several modals implemented, but didn't get to finish the rebase (branch selection) due to context switching (being pulled in different directions all the time), so since you're working on this now, I spent time today getting back to this to share what the modal would look like.

The biggest change I've made is splitting out repo management from an all-in-one UI, as you don't really edit repos all that frequently. Generally, you're more concerned with branches. Branch rebasing is usually not a frequent action either, but it's much more common (especially on Silverblue) than repo editing.

As a result, the revised main page would look like this (the change is removing the edit button and making it a kebab):

![OStree page](https://user-images.githubusercontent.com/10246/222146980-49685eb8-83c3-45b8-b946-a7f56ef96035.png)

And here's what's hiding there in the menu:

![Source kebab](https://user-images.githubusercontent.com/10246/222150090-06607e78-e9c1-41a2-81a1-719c352bcca3.png)

And these are the dialogs for the actions:

![Rebase - 1 repo](https://user-images.githubusercontent.com/10246/222150338-37b4f64c-63c4-4b41-9309-ab5ff8e2d138.png)
(When there's only 1 repo, the selector is not there. It's just text.)

![Rebase- 2 or more](https://user-images.githubusercontent.com/10246/222151353-ac4172f6-6b3d-4646-af5b-07edec6a8638.png)
(When theres > 1 repo, the repo list is hidden away in a dropdown. Usually, I wouldn't suggest a dropdown for things that are  less than 4 or 5, but generally, someone would never switch this, so it's a way to hide away things that almost never matter, but still allow for a choice.)

![Add repository](https://user-images.githubusercontent.com/10246/222150410-57ec90fb-e30b-4a42-813f-9dfa6d2efb4c.png)
Adding gets its own dialog. It's too complex otherwise.

![Remove repository](https://user-images.githubusercontent.com/10246/222150776-cef632e1-19db-4ad8-a4c1-09186cccaeb9.png)
Currently selected repository is disabled. Items are not checked by default. The "Remove" button would be disabled when nothing is checked.

2023-03-01 13:25 UTC, garrett requested changes
Please change according the the new mockups, based on the current mockups (and not the 2 year old mockups).

Thanks! :+1:

2023-03-20 11:46 UTC, marusak commented
@garrett what about "edit" repo action? How would user pick which repo they want to edit?

2023-03-20 15:49 UTC, garrett commented
@marusak: It'd use the modal dialogs, as mocked up above?

I spec'd it out as a kebab menu with rebase, add, and remove. The point of the redesign is that we were trying to do everything at the same time, which doesn't make sens, so I refactored it all in the mockups in the immediately previous comment @ https://github.com/cockpit-project/cockpit-ostree/pull/339#issuecomment-1450151589.

Start with _"As a result, the revised main page would look like this"_.

2023-03-20 15:51 UTC, garrett commented
Oh, you mean edit an already added repo instead of adding and removing? Would people really use that in practice? Adding would have a validation, so you wouldn't be able to add something that doesn't exist, so therefore, you wouldn't need to edit it really, IMO.

2023-03-21 07:28 UTC, marusak commented
I think that editing is always a good practice. If we don't add it it is just matter of time before someone will come and ask for it. Same as with timers, firewall services... If user can create something from UI they should be able to edit it. Nobody likes to delete and create new one when they realize they actually need something bit different.

Moreover right now if you want to add more keys you need to do it in the edit option. This seems weird and should be fixed but for example that is usecase where you might want to edit repo when you need to use different gpg key.

2023-03-22 08:21 UTC, garrett commented
So the question is if you can only edit the currently active repo or any repo.

If it's only the current, it would be rather straightforward:

- The edit modal would be the same as the add, but with a different title and action button and have the values prefilled.
- And it would have an entry on the menu, under add; it would probably say "Edit active repository".

I literally had this mocked up and thought I exported and shared it here. Anyway, here's a fresh export:

![edit modal](https://user-images.githubusercontent.com/10246/226838704-c5950e94-a014-4953-ba89-68f89ea4716d.png)

![Source kebab(1)](https://user-images.githubusercontent.com/10246/226839516-99266f27-1b35-4855-b337-b60f709453b4.png)

---

However, remove has you select a repo to remove that isn't the current. And editing the current one might not work (you might need to rebase into anthing that's edited).

If that's the case, then we'd need to have some way to select the repo. It could be indeterminate in length, and might be very long. Considering this and that you're acting only on one and not multiple, I guess we could use a dropdown select and then have the form items below it prefilled, much like the above suggestion.

However, if we're selecting on name and also changing the name, that could be problematic — I suppose in this case, we just keep the previous name in the modal for the time being as it won't become active until the edits are saved anyway.

It'd look like this:

![image](https://user-images.githubusercontent.com/10246/226840659-5d811ee7-b9d9-4490-ab2a-20f21f23e350.png)

There's an intentional separation between the repository dropdown and the edit area.

The menu would be like the one above, but it would only say "Edit repository", as you can only edit one at a time.

2023-11-28 09:18 UTC, closed without merging